# TODO rename to OPLK_DLL and OPLK_LIB
MACRO(FIND_OPLK_LIBRARY OPLK_NODE_TYPE)

    IF(CMAKE_SYSTEM_NAME STREQUAL "Linux")

        IF(CFG_KERNEL_STACK_DIRECTLINK)
            SET(OPLKLIB_NAME oplk${OPLK_NODE_TYPE})
        ELSEIF (CFG_KERNEL_STACK_USERSPACE_DAEMON)
            SET(OPLKLIB_NAME oplk${OPLK_NODE_TYPE}app-userintf)
        ELSEIF (CFG_KERNEL_STACK_KERNEL_MODULE)
            SET(OPLKLIB_NAME oplk${OPLK_NODE_TYPE}app-kernelintf)
        ELSE()
            SET(OPLKLIB_NAME oplkUnknown)
        ENDIF (CFG_KERNEL_STACK_DIRECTLINK)

    ELSEIF(CMAKE_SYSTEM_NAME STREQUAL "Windows")
        SET(OPLKLIB_NAME oplk${OPLK_NODE_TYPE})
    ELSE()
        MESSAGE(FATAL_ERROR "Unsupported CMAKE_SYSTEM_NAME ${CMAKE_SYSTEM_NAME} or CMAKE_SYSTEM_PROCESSOR ${CMAKE_SYSTEM_PROCESSOR}")
    ENDIF()

    STRING(TOLOWER ${CMAKE_SYSTEM_NAME} CMAKE_SYSTEM_NAME_LOWER)
    SET(OPLKLIB_DEBUG_NAME "${OPLKLIB_NAME}_d")

    # Set OPLK library and include directory
    SET(OPLKLIB_DIR ${OPLK_ROOT_DIR}/stack/lib/${CMAKE_SYSTEM_NAME_LOWER}/${CMAKE_SYSTEM_PROCESSOR})
    SET(OPLKLIB_INCDIR ${OPLK_ROOT_DIR}/stack/proj/${CMAKE_SYSTEM_NAME_LOWER}/lib${OPLKLIB_NAME})


    # Search for release library
    UNSET(OPLKLIB_RELEASE CACHE)
    MESSAGE(STATUS "Searching for LIBRARY ${OPLKLIB_NAME} in ${OPLKLIB_DIR}")
    FIND_LIBRARY(OPLKLIB_RELEASE NAME ${OPLKLIB_NAME} HINTS ${OPLKLIB_DIR} )
	#${CONFIG_openPOWERLINK_CUSTOM_LIBSEARH_PATH}

    IF(CMAKE_SYSTEM_NAME STREQUAL "Windows")
        UNSET(OPLKDLL_RELEASE CACHE)
        FIND_PROGRAM(OPLKDLL_RELEASE NAME ${OPLKLIB_NAME}.dll HINTS ${OPLKLIB_DIR} )
		IF(OPLKDLL_RELEASE STREQUAL "OPLKDLL_RELEASE-NOTFOUND")
			#MESSAGE(FATAL_ERROR "${OPLKLIB_NAME}.dll NOT FOUND. Please build openPOWERLINK stack release windows dll")
		ENDIF()
    ENDIF(CMAKE_SYSTEM_NAME STREQUAL "Windows")




    # Search for debug library
    UNSET(OPLKLIB_DEBUG CACHE)
    MESSAGE(STATUS "Searching for LIBRARY ${OPLKLIB_DEBUG_NAME} in ${OPLKLIB_DIR}")
    FIND_LIBRARY(OPLKLIB_DEBUG NAME ${OPLKLIB_DEBUG_NAME} HINTS ${OPLKLIB_DIR} )

    IF(CMAKE_SYSTEM_NAME STREQUAL "Windows")
        UNSET(OPLKDLL_DEBUG CACHE)
        FIND_PROGRAM(OPLKDLL_DEBUG NAME ${OPLKLIB_DEBUG_NAME}.dll HINTS ${OPLKLIB_DIR} )
		IF(OPLKDLL_DEBUG STREQUAL "OPLKDLL_DEBUG-NOTFOUND")
			#MESSAGE(FATAL_ERROR "${OPLKLIB_DEBUG_NAME}.dll NOT FOUND. Please build openPOWERLINK stack debug windows dll")
		ENDIF()
    ENDIF(CMAKE_SYSTEM_NAME STREQUAL "Windows")

    INCLUDE_DIRECTORIES(${OPLKLIB_INCDIR})

ENDMACRO(FIND_OPLK_LIBRARY)


MACRO(FIND_OPLK_QT_WRAP_LIBRARY OPLK_QT_WRAP_LIB_NAME)
	#Set the project name for the library
	SET(OPLK_QT_WRAP_LIB_DEBUG_NAME "${OPLK_QT_WRAP_LIB_NAME}_d")

	# Search for release library
	UNSET(OPLK_QT_WRAP_LIB_RELEASE CACHE)
    MESSAGE(STATUS "Searching for LIBRARY ${OPLK_QT_WRAP_LIB_NAME} in ${OPLK_APPS_LIB_INSTALL_PREFIX}")
    FIND_LIBRARY(OPLK_QT_WRAP_LIB_RELEASE NAME ${OPLK_QT_WRAP_LIB_NAME} HINTS ${OPLK_APPS_LIB_INSTALL_PREFIX} )

    IF(CMAKE_SYSTEM_NAME STREQUAL "Windows")
        UNSET(OPLK_QT_WRAP_DLL_RELEASE CACHE)
        FIND_PROGRAM(OPLK_QT_WRAP_DLL_RELEASE NAME ${OPLK_QT_WRAP_LIB_NAME}.dll HINTS ${OPLK_APPS_LIB_INSTALL_PREFIX} )
		IF(OPLK_QT_WRAP_DLL_RELEASE STREQUAL "OPLK_QT_WRAP_DLL_RELEASE-NOTFOUND")
			#MESSAGE(FATAL_ERROR "${OPLK_QT_WRAP_LIB_NAME}.dll NOT FOUND. Please build oplkQt wrapper release windows dll")
		ENDIF()
    ENDIF(CMAKE_SYSTEM_NAME STREQUAL "Windows")

	# Search for debug library
    UNSET(OPLK_QT_WRAP_LIB_DEBUG CACHE)
    MESSAGE(STATUS "Searching for LIBRARY ${OPLK_QT_WRAP_LIB_DEBUG_NAME} in ${OPLK_APPS_LIB_INSTALL_PREFIX}")
    FIND_LIBRARY(OPLK_QT_WRAP_LIB_DEBUG NAME ${OPLK_QT_WRAP_LIB_DEBUG_NAME} HINTS ${OPLK_APPS_LIB_INSTALL_PREFIX} )

    IF(CMAKE_SYSTEM_NAME STREQUAL "Windows")
        UNSET(OPLK_QT_WRAP_DLL_DEBUG CACHE)
        FIND_PROGRAM(OPLK_QT_WRAP_DLL_DEBUG NAME ${OPLK_QT_WRAP_LIB_DEBUG_NAME}.dll HINTS ${OPLK_APPS_LIB_INSTALL_PREFIX} )
		IF(OPLK_QT_WRAP_DLL_DEBUG STREQUAL "OPLK_QT_WRAP_DLL_DEBUG-NOTFOUND")
			#MESSAGE(FATAL_ERROR "${OPLK_QT_WRAP_LIB_DEBUG_NAME}.dll NOT FOUND. Please build  oplkQt wrapper debug windows dll")
		ENDIF()
    ENDIF(CMAKE_SYSTEM_NAME STREQUAL "Windows")

	INCLUDE_DIRECTORIES(${OPLK_QT_WRAP_INCLUDE_DIR})

ENDMACRO(FIND_OPLK_QT_WRAP_LIBRARY)