SET(CONFIG_openPOWERLINK_BUILD_TYPE "Link to Application"
	CACHE STRING "Configure how to build the kernel stack")

SET(openPOWERLINK_StackBuildTypes
	"Link to Application;Linux Userspace Daemon;Linux Kernel Module;None"
	CACHE INTERNAL "List of possible kernel stack build types")

SET_PROPERTY(CACHE CONFIG_openPOWERLINK_BUILD_TYPE
			 PROPERTY STRINGS ${openPOWERLINK_StackBuildTypes})

IF (CONFIG_openPOWERLINK_BUILD_TYPE STREQUAL "Link to Application")

	SET (CFG_KERNEL_STACK_DIRECTLINK ON CACHE INTERNAL
		 "Link kernel stack directly into application (Single process solution)")
	UNSET (CFG_KERNEL_STACK_USERSPACE_DAEMON CACHE)
	UNSET (CFG_KERNEL_STACK_KERNEL_MODULE CACHE)

ELSEIF (CONFIG_openPOWERLINK_BUILD_TYPE STREQUAL "Linux Userspace Daemon")

	SET (CFG_KERNEL_STACK_USERSPACE_DAEMON ON CACHE INTERNAL
		 "Build kernel stack as Linux userspace daemon")
	UNSET (CFG_KERNEL_STACK_DIRECTLINK CACHE)
	UNSET (CFG_KERNEL_STACK_KERNEL_MODULE CACHE)

ELSEIF (CONFIG_openPOWERLINK_BUILD_TYPE STREQUAL "Linux Kernel Module")

	SET (CFG_KERNEL_STACK_KERNEL_MODULE ON CACHE INTERNAL
		 "Build kernel stack as Linux kernelspace module")
	UNSET (CFG_KERNEL_STACK_USERSPACE_DAEMON CACHE)
	UNSET (CFG_KERNEL_STACK_DIRECTLINK CACHE)

ELSEIF (CONFIG_openPOWERLINK_BUILD_TYPE STREQUAL "None")
	UNSET (CFG_KERNEL_STACK_USERSPACE_DAEMON CACHE)
	UNSET (CFG_KERNEL_STACK_KERNEL_MODULE CACHE)
	UNSET (CFG_KERNEL_STACK_DIRECTLINK CACHE)
ENDIF (CONFIG_openPOWERLINK_BUILD_TYPE STREQUAL "Link to Application")
